# SPDX-FileCopyrightText: 2025 Copyright (c) 2025 Konstantinas Mesnikas
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "*.neon",
    "composer.json",
    "composer.lock",
    "README.md",
    ".gitignore"
]

precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2025 Konstantinas Mesnikas"
SPDX-License-Identifier = "MIT"